Todo/urls.py
from django.urls import path
from . import views
app_name='todo'
urlpatterns = [
# Todo List Operations
    path('',views.show,name='show'),
    path('<int:id>/',views.show,name='show'),
    path('search/<str:search>/',views.show,name='search'),
    path('details/<int:pk>/',views.Details.as_view(),name='details'),
    path('create/',views.Create.as_view(),name='create'),
    path('update/<int:pk>',views.Update.as_view(),name='update'),
    path('delete/<int:pk>/',views.Delete.as_view(),name='delete'),
    path('export/',views.export,name='export'),
]

Todo_list/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
urlpatterns = [
    # Inbuilt Admin Panel
    path('admin/', admin.site.urls),
    # Main App Route
    path('',include('Todo.urls',namespace='todo')),
    # Users Route
    path('auth1/',include('auth1.urls')),
    # API Route
    path('api/',include('Todo_api.urls')),
    path('rest_auth/',include('rest_auth.urls')),

    # Password Change links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),
    # Password Reset links
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

templates/create.html
{% extends 'layout.html' %}
{% block content %}
<main role="main" class="container">
    
    <div class="my-2 p-3 bg-white rounded shadow-sm">
        <div class="container">
            <h6 class="border-bottom border-gray pb-2 mb-0">Create New</h6>
            <form class="form-row" method="POST">
                {% csrf_token %}
                <div class="col-md-3 order-md-1">
                    {{form.name.label_tag}}
                    {{form.name}}
                    <hr>
                    <div align="center">
                        <input tabindex="3" class="btn btn-sm btn-primary" type="submit" value="Add">
                        <a tabindex="4" class="btn btn-sm btn-secondary" href="{% url 'todo:show' %}">Cancel</a>
                    </div>
                </div>
                <div class="col-md-9 order-md-2">
                    {{form.data.label_tag}}
                    {{form.data}}<br>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/details.html
{% extends 'layout.html' %}
{% block content %}
<main role="main" class="container">
    
    <div class="my-2 p-3 bg-white rounded shadow-sm">
        <div class="container">
            <form class="form-row" method="POST">
                {% csrf_token %}
                <div class="col-md-12 order-md-1">
                    <h4><b>{{object.name}}</b>: Detail View <u>Created on</u>: {{object.date_created}}</h4><hr>
                    <h5>
                        {{object.data|linebreaksbr}}
                    </h5>
                    <hr>
                    <small class="d-block text-right mt-3">
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'todo:show' object.id %}">
                            {% if object.status == False %}Pending{% else %}Checked{% endif %}
                        </a>  
                        <a class="btn btn-sm btn-outline-primary" href="{% url 'todo:update' object.pk %}">Edit</a>
                        <a class="btn btn-sm btn-outline-danger" href="{% url 'todo:delete' pk=object.pk %}">Delete</a>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'todo:show' %}">back</a>
                    </small>
                </div>
                <div class="col-md-9 order-md-2">
                    {{form.data.label_tag}}
                    {{form.data}}<br>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>My Todo</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
    <link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">
</head>

<body class="bg-light">
    <div class="container">
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="collapse navbar-collapse">
            
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'edit_profile' %}">Profile</a>
                    <a class="navbar-brand" href="{% url 'todo:show' %}">Show List</a>
                    <a class="navbar-brand" href="{% url 'todo:create' %}">Create New Todo</a>
                    <h4 style="color: rgb(255, 255, 255);" class="navbar-collapse">Welcome, {{user}}</h4>
                    <a class="navbar-brand" href="javascript:{document.getElementById('delete').submit()}">Logout</a>
                    <form method="POST" id="delete" action="{% url 'signout' %}">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                {% else %}
                    <a class="navbar-brand" href="{% url 'signin' %}">Login!</a>
                    <a class="navbar-brand" href="{% url 'signup' %}">Signup!</a>
                {% endif %}
        </div>
    </nav>
    </div>
    <br><br><br>
    <h3 align="center">My Todo</h3>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/layout2.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>My Todo</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: start;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        body {
            background-color: rgb(243, 230, 219);
            background-size: 100%;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom shadow-lg">
        <a class="navbar-brand" href="#">Aradhya</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'edit_profile' %}">Profile<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Gallery</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Patient Data</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Doctors Data<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">OPD Record</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Daily Collection</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="">Career</a>
                </li>

                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'career' %}">Career</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contactus' %}">Contact Us</a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" href="javascript:{document.getElementById('delete').submit()}">Logout</a>
                </li>
                <form method="POST" id="delete" action="{% url 'signout' %}">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
                {% endif %}
            </ul>
        </div>
    </nav>
    <br>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <!-- Social Media Buttons Links from W3 School -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</body>

</html>

templates/show.html
{% extends 'layout.html' %}
{% block content %}
<main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <h6 class="border-bottom border-gray pb-2 mb-0">Todo List -
            <label style="color: #007bff;">Checked</label>/<label style="color:#ff0000">Pending <label
                    style="color: black;">No. of items = {{object_list | length}}</label></label>
            <label>
                <form action="/search/'search'" class="form-inline my-2 my-lg-0">{% csrf_token %}
                    <input required autofocus="true" name="search" class="form-control mr-sm-3" value="{{search}}" type="text"
                        placeholder="Search by name" aria-label="Search">
                    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">
                </form>
            </label>
            <a href="{% url 'todo:export' %}">Export to Text File</a>
            {% if session_export %}
                <script type="text/javascript">
                    var session = "{{session_export}}"
                    alert(session)
                </script>
            {% endif %}            
            {% if session_login_check %}
            <label style="color: green;">{{session_login_check}}</label>
            {% endif %}
        </h6>
        {% for data in object_list %}
        <div class="media text-muted pt-3">
            <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg"
                preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32">
                <title>Placeholder</title>
                {% if data.status == False %}
                <rect width="100%" height="100%" fill="#ff0000" /><text x="50%" y="50%" fill="#ff0000"
                    dy=".3em">32x32</text>
                {% else %}
                <rect width="100%" height="100%" fill="#007bff" /><text x="50%" y="50%" fill="#007bff"
                    dy=".3em">32x32</text>
                {% endif %}
            </svg>
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{data.name}}</strong>{{ data.data|slice:":130" }}
                ...<small style="color: blue;">click on View</small>
            </p>
            <small class="d-block text-right mt-3"> 
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'todo:show' data.id %}">
                    {% if data.status == False %}Pending{% else %}Checked{% endif %}
                </a>                
                <a class="btn btn-sm btn-outline-primary" href="{{data.get_absolute_url}}">View</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'todo:delete' pk=data.pk %}">Delete</a>
            </small>
        </div>
        {% endfor %}
        <nav>
          <ul class="pagination">
              <!-- Previous page link -->
            {% if object_list.has_previous %}
            <li class="page-item"><a href="?page={{object_list.previous_page_number}}" class="page-link">Previous</a></li>
           
            {% endif %}
            <!-- Page Numbers -->
            {% for p in object_list.paginator.page_range %}
                {% if p == object_list.number %}
                    <li class="page-item active"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
                {% endif %}
            {% endfor %}
            <!-- Next Page link -->
            {% if object_list.has_next %}
            <li class="page-item"><a href="?page={{object_list.next_page_number}}" class="page-link">Next</a></li>
            {% endif %}
          </ul>
        </nav>
    </div>
</main>
{% endblock %}